BookStore/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using BookStore.Helper;
using Microsoft.AspNetCore.Http;

namespace BookStore.Models
{
    public class Book
    {
        public int Id { get; set; }

        //[Required(ErrorMessage = "Please enter the title of your book")]
        [StringLength(100, MinimumLength = 5)]
        [Required(ErrorMessage = "Please enter book title")]
        [MyCustomValAttr("book")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please enter the author name")]
        public string Author { get; set; }

        [StringLength(500)]
        public string Description { get; set; }

        public string Category { get; set; }
        
        public int LanguageId { get; set; }
        public string Language { get; set; }

        [Required(ErrorMessage = "Please enter the total pages")]
        [Display(Name = "Total pages of book")]
        public int? TotalPages { get; set; }

        [Display(Name = "Choose a photo your book")]
        [Required]
        public IFormFile CoverFoto { get; set; }
        public string CoverImageUrl { get; set; }

        [Display(Name = "Choose a gallery photo of your book")]
        [Required]
        public IFormFileCollection GalleryFiles { get; set; }

        public List<GalleryModel> Gallery { get; set; }
        
        [Display(Name = "Upload your book in pdf format")]
        [Required]
        public IFormFile BookPdf { get; set; }
        public string BookPdfUrl { get; set; }
    }
}

BookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Models;
using BookStore.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookStore.Controllers
{
    [Route("[controller]/[action]")]
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository = null;
        private readonly ILanguageRepository _languageRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BookController(IBookRepository bookRepository, ILanguageRepository languageRepository, IWebHostEnvironment webHostEnvironment)
        {
            _bookRepository = bookRepository;
            _languageRepository = languageRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [Route("~/all-books")]
        public async Task<ViewResult> getAllBooks()
        {
            var data = await _bookRepository.getAllBooks();

            return View(data);
        }

        [Route("~/book-detail/{id}", Name = "book.detail")]
        public async Task<ViewResult> getBook(int id)
        {
            var data = await _bookRepository.getBookById(id);

            return View(data);
        }

        public List<Book> searchBooks(string name, string author)
        {
            return _bookRepository.searchBook(name, author);
        }

        [Authorize]
        public async Task<ViewResult> addBook(bool isSuccess = false, int bookId = 0)
        {
            var model = new Book()
            {
                //Language = "2"
            };            
          
            ViewBag.isSuccess = isSuccess;
            ViewBag.bookId = bookId;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> addBook(Book book)
        {
            if (ModelState.IsValid)
            {
                if (book.CoverFoto != null)
                {
                    string folder = "books/cover/";
                    book.CoverImageUrl = await UploadImage(folder, book.CoverFoto);
                }

                if (book.GalleryFiles != null)
                {
                    string folder = "books/gallery/";
                    book.Gallery = new List<GalleryModel>();

                    foreach (var file in book.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.FileName,
                            URL = await UploadImage(folder, file),
                        };

                        book.Gallery.Add(gallery);                        
                    }
                    
                }

                if (book.BookPdf != null)
                {
                    string folder = "books/pdf/";
                    book.BookPdfUrl = await UploadImage(folder, book.BookPdf);
                }

                int id = await _bookRepository.addNewBook(book);
                if (id > 0)
                {
                    return RedirectToAction(nameof(addBook), new { isSuccess = true, bookId = id });
                }
            }            

            return View();
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {            
            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;            

            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return "/" + folderPath;
        }
    }
}

BookStore/Views/Book/AddBook.cshtml
@model Book
@inject BookStore.Repository.ILanguageRepository _languangeRepo
@{
    ViewData["Title"] = "Add New Book";
}

<div class="container">
    <h3 class="display-4">Add New Book</h3>
    <hr />
    @if (ViewBag.isSuccess == true)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Add Successully</strong> you added new book successfully.<br />
            Click <a asp-controller="Book" asp-action="getBook" asp-route-id="@ViewBag.bookId">here</a> to view details
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            </button>
        </div>
    }

    @*<div class="d-flex justify-content-center">
        <div class="spinner-border" role="status" id="myLoader" style="display:none;">
            <span class="sr-only">Loading...</span>
        </div>
    </div>*@

<form method="post" enctype="multipart/form-data" asp-action="AddBook" asp-controller="Book">
    @*<div asp-validation-summary="All" class="text-danger"> </div>*@
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" class="form-control" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="LanguageId"></label>
        <select asp-for="LanguageId" class="form-control" asp-items="(await _languangeRepo.GetLanguages()).Select(x=> new SelectListItem() { Text = x.Name, Value = x.Id.ToString()})">
            <option value="">Please choose a language</option>
        </select>
        <span asp-validation-for="LanguageId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TotalPages"></label>
        <input asp-for="TotalPages" class="form-control" />
        <span asp-validation-for="TotalPages" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CoverFoto" class="form-label"></label>
        <div class="mb-3">
            <input asp-for="CoverFoto" class="form-control" type="file" id="formFile">
        </div>
        <span asp-validation-for="CoverFoto" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="GalleryFiles" class="form-label"></label>
        <div class="mb-3">
            <input asp-for="GalleryFiles" class="form-control" type="file" id="formFile" multiple="">
        </div>
        <span asp-validation-for="GalleryFiles" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BookPdf" class="form-label"></label>
        <div class="mb-3">
            <input asp-for="BookPdf" class="form-control" type="file" id="formFile">
        </div>
        <span asp-validation-for="BookPdf" class="text-danger"></span>
    </div>  

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Add Book</button>
    </div>
</form>
</div>

@*@section scripts {
    <script>
        function myComplete(data) {
            alert("Complete");
            console.log(data);
        }

        function mySuccess(data) {
            alert("Success");
            console.log(data);
        }

        function myFailure(data) {
            alert("Failure");
            console.log(data);
        }
    </script>*@
}

BookStore/Views/Book/GetAllBooks.cshtml
@model IEnumerable<Book>
@{
    ViewData["Title"] = "List Book";
}

<div class="container">
    <h3 class="display-4">All book list</h3>
    <div class="row">
        @foreach (var book in Model)
        {
            <div class="col-md-4">
                <partial name="_bookThumbnail" model="@book"/>                
            </div>
        }

    </div>
</div>

BookStore/Views/Book/GetBook.cshtml
@model Book;
@{
    ViewData["Title"] = Model.Title;
}

<div class="container">
    <h3 class="display-4">Book details</h3>
    <div class="row">
        <div class="col-md-6">
            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                <ol class="carousel-indicators">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                      <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="@i" class="@(i == 0 ? "active":"")"></li>
                    }                    
                </ol>
                <div class="carousel-inner">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                    <div class="@(i == 0 ? "carousel-item active":"carousel-item")" data-bs-interval="2000">
                        <img src="@Model.Gallery[i].URL" asp-append-version="true" class="d-block w-100" alt="@Model.Gallery[i].Name" />                        
                    </div>
                    }
                </div>
                <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </a>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Title</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-primary">
                    <span>By : </span>
                    <span class="text-monospace">@Model.Author</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p class="description">
                        @Model.Description
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <a class="btn btn-outline-primary" href="@Model.BookPdfUrl" target="_blank">
                        Read Now
                    </a>
                </div>
            </div>

            <hr />

            <ul class="list-group">
                <li class="list-group-item"><span class="font-weight-bold">Category - </span>@Model.Category</li>
                <li class="list-group-item"><span class="font-weight-bold">Total pages - </span>@Model.TotalPages</li>
                <li class="list-group-item"><span class="font-weight-bold">Language - </span>@Model.LanguageId</li>
            </ul>
        </div>
    </div>

    <hr />

    <div class="py-5 bg-light" id="similiarBooks">
        <h3 class="h3">Similiar books</h3>
        <div class="row">
            @for (int i = 0; i < 5; i++)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <svg class="card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"></svg>
                        <div class="card-body">
                            <h3 class="card-title">book.Title</h3>
                            <p class="card-text">book.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="#" class="btn btn-sm btn-outline-secondary">View details</a>
                                </div>
                                <small class="text-muted">book.Author</small>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>